### ISSUE TITLE
Failure when adding a filter

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-provider-google-sheets#10]
https://harvey.koopernetes.com/googlesheets/1C1ml2-Dte8Hjsa0FJ1I7BxlnfYz0eTFxQzw3rq8UtJY/Combined!A1:U/FeatureServer/0/query?f=json&where=Status%20%3C%3E%20%27Duplicate%27&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-10488383.273183048%2C%22ymin%22%3A3443946.7464246303%2C%22xmax%22%3A-10331840.239255084%2C%22ymax%22%3A3600489.7803525943%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

```json
{
"error": "Parse error on line 1:\n...roperties->`Status` properties->`<` > 'D\n-----------------------^\nExpecting 'EOF', 'WITH', 'RPAR', 'IN', 'LIKE', 'ARROW', 'DOT', 'ORDER', 'CARET', 'EQ', 'SLASH', 'EXCLAMATION', 'MODULO', 'GT', 'LT', 'GTGT', 'LTLT', 'NOT', 'UNION', 'INTERSECT', 'EXCEPT', 'AND', 'OR', 'PLUS', 'STAR', 'GROUP', 'LIMIT', 'OFFSET', 'END', 'ELSE', 'REGEXP', 'TILDA', 'GLOB', 'NOT_LIKE', 'BARBAR', 'MINUS', 'AMPERSAND', 'BAR', 'GE', 'LE', 'EQEQ', 'EQEQEQ', 'NE', 'NEEQEQ', 'NEEQEQEQ', 'BETWEEN', 'NOT_BETWEEN', 'IS', 'DOUBLECOLON', 'GO', 'SEMICOLON', got 'LITERAL'"
}
```

**Comment by jgravois** [comment]
not sure whether this is a problem in winnow or perhaps a known limitation deeper down in AlaSQL. i'll dig in deeper tomorrow, in the meantime, can you use this syntax instead?

~~Status <> 'Duplicate'~~ / NOT Status = 'Duplicate'


http://harvey.koopernetes.com/googlesheets/1C1ml2-Dte8Hjsa0FJ1I7BxlnfYz0eTFxQzw3rq8UtJY/Combined!A1:U/FeatureServer/0/query?f=json&where=NOT%20Status=%27Duplicate%27&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-10488383.273183048%2C%22ymin%22%3A3443946.7464246303%2C%22xmax%22%3A-10331840.239255084%2C%22ymax%22%3A3600489.7803525943%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&outSR=102100

**Comment by ajturner** [comment]
@jgravois I was using the Map editor UI. Not sure what you can do there for other options

**Comment by slibby** [comment]
I believe this is no longer an issue.
