### ISSUE TITLE
Issue working with polygons

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop-provider-google-sheets#11]
Hi @dmfenton, 

I'm playing a little bit with this provider but I'm having some issues:

1. I'm trying to match the name of the "Provincia" (*~state*) of each row of [this spreadsheet](https://docs.google.com/spreadsheets/d/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/edit?usp=sharing) with a [boundaries file](https://gist.githubusercontent.com/hhkaos/cd410181e59e8b6271d6ba0262b5a24d/raw/41139f8d130099b8e02e6400ad8c6cf144c8d535/provincias.json) I have on my local. And the [geojson generated](https://gist.github.com/hhkaos/cd410181e59e8b6271d6ba0262b5a24d) seems to be OK.
2. Now when I query the provider the [output is this](https://koopjsprovider-google-sheets-xxrbtezfdn.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0/query), which at first seems to be OK too.
3. But when I try to [load it in the webmap viewer](http://www.arcgis.com/home/webmap/viewer.html?url=https://koopjsprovider-google-sheets-xxrbtezfdn.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0) it is not displaying the geometries as you can see here:

[![screen shot 2018-05-02 at 14 27 27](https://user-images.githubusercontent.com/826965/39523193-077afac2-4e15-11e8-98cd-a22221aa185f.png)](http://www.arcgis.com/home/webmap/viewer.html?url=https://koopjsprovider-google-sheets-xxrbtezfdn.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0)

> Because I wasn't sure if the problem was with the way I was generating the geometries, I also tested the output with [geojsonhint](https://github.com/mapbox/geojsonhint) and it only displayed a `warning  Polygons and MultiPolygons should follow the right-hand rule`, so I continued testing:

4. I uploaded the 
[GeoJSON](https://gist.github.com/hhkaos/cd410181e59e8b6271d6ba0262b5a24d) I was passing to `callback(null, geojson)` though the "Content" tab to generate a [new item with the hosted feature service](http://www.arcgis.com/home/item.html?id=605e334b1c5048df9e4d04edcdf69704)
5. And, as I expected, [from the visualization tab](http://hhkaos2.maps.arcgis.com/home/item.html?id=605e334b1c5048df9e4d04edcdf69704#visualize) it couldn't see the geometries either
6. But the weird thing comes now, if I [load it to the webmap viewer directly](http://www.arcgis.com/home/webmap/viewer.html?layers=605e334b1c5048df9e4d04edcdf69704), it worked 😮

![screen shot 2018-05-02 at 14 35 22](https://user-images.githubusercontent.com/826965/39523490-15dca592-4e16-11e8-84a4-1eee1c12da45.png)

So, I have no idea on what's happening, is there any way I can test/debug the output from Koop? Something like a "FeatureService linter", or do you have any clue on what's going on?

By the way, I also tried to use "[the Exporter](https://github.com/koopjs/koop/issues/195#issuecomment-115072181)" but it [doesn't work here](https://koopjsprovider-google-sheets-xxrbtezfdn.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0/query.geojson), right?

These are the modifications I have done:

```javascript

const google = require('googleapis')
const config = require('./config/production.json')
const provincias = require('./output.json')
const sheets = google.sheets('v4')
const XVARS = ['x', 'longitude', 'lon', 'longitud', 'Lon']
const YVARS = ['y', 'latitude', 'lat', 'latitud', 'Lat']

function GoogleSheets () {}

GoogleSheets.prototype.getData = function getData (req, callback) {
  const spreadsheetId = req.params.host  // e.g. 1JlPaiuIHXmkfpLBaQdoRixPSasjX5NlDte70pyFT9yI OR 1dK_touGylnTtJBzve2HEwfev_f6JxCpRMb2NZ-LMI1g  ::Providers have built-in support for capturing request params, aka. googlesheets/:host/:id/FeatureServer/0
  const range = req.params.id // e.g. Park Cleanup!A1:H  OR World Cities!A1:I
  const gsOpts = {
    auth: config.googlesheets.auth,
    spreadsheetId, // e.g. https://docs.google.com/spreadsheets/d/1JlPaiuIHXmkfpLBaQdoRixPSasjX5NlDte70pyFT9yI/edit?usp=sharing
    range
  }
  sheets.spreadsheets.values.get(gsOpts, (err, res) => {
    if (err) return callback(err)
    const geojson = translate(res)
    geojson.ttl = config.googlesheets.ttl || 1200 // 20 minutes
    geojson.metadata = {
      name: range.split('!')[0], // Get the workbook name before ! symbol and set as layer name
      description: 'Collaborate in Google docs, analyse in ArcGIS'
    }

    var fs = require('fs');
    fs.writeFile("result.json", JSON.stringify(geojson, null, 2), function(err) {
        if(err) {
            return console.log(err);
        }

        console.log("The file was saved!");
    });

    callback(null, geojson)
  })
}

function translate (response) {
  const propertyNames = createPropertyNames(response.values[0])
  return {
    type: 'FeatureCollection',
    features: response.values.slice(1).map(row => { return formatFeature(row, propertyNames) })
  }
}

function formatFeature (row, propertyNames) {
  const x = propertyNames.indexOf('x')
  const y = propertyNames.indexOf('y')
  if(x != -1 && y != -1){
      return {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [parseFloat(row[x]), parseFloat(row[y])] // Make sure coordinates are numbers not strings
        },
        properties: row.reduce((props, prop, i) => {
          if (i !== x && i !== y) props[propertyNames[i]] = prop
          return props
        }, {})
      }
  }else{

      const coordinates = propertyNames.indexOf('PROVINCIAS')
      var slugyField = slugify(row[coordinates]);

      switch(slugyField){
          case 'baleares':
          slugyField = 'balears-illes';
          break;
          case 'las-palmas':
          slugyField = 'palmas-las';
          break;
          case 'sta-cruz':
          slugyField = 'santa-cruz-de-tenerife';
          break;
          case 'araba':
          slugyField = 'arabalava';
          break;
          case 'a-corua':
          slugyField = 'corua-a';
          break;
          case 'orense':
          slugyField = 'ourense';
          break;
          case 'la-rioja':
          slugyField = 'rioja-la';
          break;
          case 'alicante':
          slugyField = 'alicantealacant';
          break;
          case 'castelln':
          slugyField = 'castellncastell';
          break;
          case 'valencia':
          slugyField = 'valenciavalncia';
          break;

      }
      if(!provincias[slugyField]){
          console.log("slugyField=",slugyField)
          console.log("provincias[slugyField]]=",provincias[slugyField])
      }

      var obj = {
        type: 'Feature',
        geometry: provincias[slugyField],
        properties: row.reduce((props, prop, i) => {
          if (i !== x && i !== y) props[propertyNames[i]] = prop
          return props
        }, {})
      };

      return obj;
  }
}

function createPropertyNames (header) {
  return header.map(head => {
    const candidate = head.toLowerCase()
    if (YVARS.indexOf(candidate) > -1) return 'y'
    else if (XVARS.indexOf(candidate) > -1) return 'x'
    else return head
  })
}

function slugify(text)
{
  return text.toString().toLowerCase()
    .replace(/\s+/g, '-')           // Replace spaces with -
    .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
    .replace(/\-\-+/g, '-')         // Replace multiple - with single -
    .replace(/^-+/, '')             // Trim - from start of text
    .replace(/-+$/, '');            // Trim - from end of text
}


module.exports = GoogleSheets
```

Thanks in advance!

**Comment by hhkaos** [comment]
Or maybe... @jgravois @slibby @ajturner can help me here ^_^

**Comment by hhkaos** [comment]
Ah, and I forgot to mention that at first I tried to [load the boundaries directly into the cell](https://docs.google.com/spreadsheets/d/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/edit#gid=1908252207) and it was working with a couple of them, but then, I had a problem with the maximum number of characters I could add to a single cell ([50000](https://i.stack.imgur.com/ig6D9.png)), that's why I started using a local file with the boundaries.

**Comment by hhkaos** [comment]
thanks Daniel :)

**Comment by rgwozdz** [comment]
@hhkaos the first thing I would do to debug is open up Chrome Dev Tools or Fiddler and inspect the requests/responses issued by the web-map-viewer to koop that return responses that fail to render.  That or those requests will likely have querystring parameters that are modifying the request and have an effect on the response.  Feel free to paste that request URL here and I can also take a look at the response;  it's possible that something is missing from the response that the map-viewer needs; if we find what's missing we can try to track down the source of the omission.

**Comment by rgwozdz** [comment]
@hhkaos - also, upgrade your instance with yarn so that you are using FeatureServer 2.12.0 and winnow 1.15.2.  That will put us at the same starting point.

**Comment by hhkaos** [comment]
Thanks Rich!, I have been out of the office but next week I'll follow your advices. Thank you very much for your help!!

**Comment by hhkaos** [comment]
Hi @rgwozdz sorry for taking so long to answer. I've updated my instance with Yarn and I have notice a warning message is showing up in the console: `WARNING: requested provider has no "idField" assignment. This can cause errors in ArcGIS clients`. 

So I have added the `idField` to the metadata but I think it is still taking the OBJECTID from somewhere else.

If have also uploaded the source code to [this repo](https://github.com/equipoimcre/09mapaeries/) and **tried to deploy** again the [NOW service](https://koopjsprovider-google-sheets-gmeyoshsie.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0/query). Not sure if it worked properly, is there any way to check by URL which versions of the FeatureServer and Winnow server are been used by the service?

I have also checked the console and I can not see any error message related to this service:

![screen shot 2018-05-21 at 10 55 49](https://user-images.githubusercontent.com/826965/40299128-8f82f8d2-5ce5-11e8-9f46-b3e7ad1ee22d.png)

The one you see is because of a Diigo extension I have installed in Chrome (but it is always there ;P).

The viewer is requesting this URLs:

* [Request with: ?f=json&callback=dojo_request_script_callbacks.dojo_request_script1](https://koopjsprovider-google-sheets-gmeyoshsie.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0?f=json&callback=dojo_request_script_callbacks.dojo_request_script1)
* [Request with: ?f=json](https://www.arcgis.com/sharing/proxy?https://koopjsprovider-google-sheets-gmeyoshsie.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0?f=json)
* [Request with: ?f=json&returnIdsOnly=true&returnCountOnly=true&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&callback=dojo_request_script_callbacks.dojo_request_script2](https://koopjsprovider-google-sheets-gmeyoshsie.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&callback=dojo_request_script_callbacks.dojo_request_script2)
* [Request with: ?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=OBJECTID%20ASC&resultOffset=0&resultRecordCount=50&callback=dojo_request_script_callbacks.dojo_request_script3](https://koopjsprovider-google-sheets-gmeyoshsie.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=OBJECTID%20ASC&resultOffset=0&resultRecordCount=50&callback=dojo_request_script_callbacks.dojo_request_script3)

But none seem to fail... and the service is still been identified as a table when it should be identified as a feature service 😞. 

Thanks again!,
Raul

**Comment by rgwozdz** [comment]
@hhkaos is the repo https://github.com/equipoimcre/09mapaeries/ private? I get a 404.

**Comment by hhkaos** [comment]
Sorry Rich, you're right, my colleagues asked me to make it private temporarily (because some dependencies need to be fixed).

**Comment by rgwozdz** [comment]
@hhkaos are you able to share your `config/production.json` file with me?  I can help debug if you send that my way.

**Comment by hhkaos** [comment]
I have share it by email with you (because of the private key), thank you very much ! :smile:

**Comment by rgwozdz** [comment]
Looks like you need to define the `geometryType` in the `metadata` object of your provider (https://github.com/equipoimcre/09mapaeries/blob/master/sheets.js#L22-L26):

`geometryType: 'MultiPolygon'`

When I add that in, I get the data returned as type `Feature Layer`.

**Comment by hhkaos** [comment]
Awesome Rich! It looks like [it is partially working](http://hhkaos2.maps.arcgis.com/home/webmap/viewer.html?url=https://koopjsprovider-google-sheets-rlcjiowwpc.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0) but for some reason not all the geometries are been displayed. I'll check again asap. Thanks!!!

**Comment by hhkaos** [comment]
mmmm I have notice the geometries are there but they are not displayed by default, for some strange reason when I span&zoom the map different geometries become visible as you can see here:

![koop strange behaviour2](https://user-images.githubusercontent.com/826965/40357103-68106fba-5dbb-11e8-93f1-fd13b8bf2e8c.gif)

Do you know why? :worried:

**Comment by rgwozdz** [comment]
That's odd.  I'll take a look.

**Comment by rgwozdz** [comment]
@hhkaos - The data in your `idField` column are not being cast as integers in your provider; rather, they arrive from google-sheets as a character string.  As a result your OBJECTIDs are also character-strings, but they need to be integers in the range of 0 to 2147483647;  you should actually see a warning in the console stating this problem with your OBJECTIDs.  I've seen issues like this cause rendering problems before.  Try explicitly casting your `idField` data to an integer in the `formatFeature` function.

**Comment by hhkaos** [comment]
Awesome @rgwozdz [it works now](http://www.arcgis.com/home/webmap/viewer.html?url=https://koopjsprovider-google-sheets-udskelpziq.now.sh/googlesheets/18eros9Yk8dD7IFlLiSsiV9AI1YT33_5OBxDpj5tCznE/Niveles!A1:J/FeatureServer/0)!! Thank you very very much!

Do you think we can improve the documentation about Koop providers to add this issues?:

* Add the `idField` and the `geometryType` to the metadata property
* And ensure the `idField` is an integer?

Thank you very very much Rich, I owe you a beer/coke in the next DevSummit ;D

**Comment by hhkaos** [comment]
Is the any way to clear the cache? (I'm updating the spreadsheet but I can't see the changes in the service yet) ^_^

**Comment by rgwozdz** [comment]
@hhkaos - very happy I was able to assist.  Improvement of the docs is something I'm hoping to undertake very soon.  The `idField` and `geometryType` metadata are noted in the Metadata section of this [page](http://koopjs.github.io/docs/specs/provider/) but perhaps it's not quite visible enough.  Any suggestion on better placement or organization of this page so that things are more clear?

As far as clearing the cache, I think you may just have to stop and restart the koop server.

**Comment by hhkaos** [comment]
You are completely right Rich. 

Maybe I would add to Koop:

* Some additional checking to verify the `idField` in an `Integer`
* Some checking to validate the OBJECTID value is in the right range
* Also include links to the documentations when something fails (and/or even a "bip" sound on the console to get the developer attention)
* Even a debuging guide or tips&tricks section would be nice

I would assume many people won't carefully read many things.

I'm glad to start contributing if you point me to the right file where this enhancements should be done (I'm still not very familiar with the whole project :sweat_smile:).

Thanks!

**Comment by rgwozdz** [comment]
We have you're first two suggestions covered here: https://github.com/koopjs/winnow/blob/master/src/executeQuery.js#L84-L86.  That was the warning that gave me the clue about your issue.  It is just a warning though, and lets Koop continue to run.  

Thanks for the feedback.

**Comment by rgwozdz** [comment]
@hhkaos - I've add this [issue](https://github.com/koopjs/koop/issues/324), suggesting we colorize the warning messages. We're always looking for contributors, so don't hesitate to take a crack at this if you'd like.
