### ISSUE TITLE
Add support for `long`

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-provider-google-sheets#8]
`long` is longitude

https://docs.google.com/spreadsheets/d/1VgIkYxZDcMBG5dZiWt4nCLlQ2yU_Y4JBRplHGfstMuQ/edit#gid=2060510034

and deploy Harvey

**Comment by slibby** [comment]
This is now supported, see https://github.com/koopjs/koop-provider-google-sheets/blob/master/sheets.js#L4
